# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo.Location'),
        ),
    ]
