# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-04 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20210701_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['date_upload']},
        ),
    ]
